services:
  - type: web
    name: Time
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=10000"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:sgZSTVZ/bYn4xLDC/P4f2/4DBwbD5REzahxVeXumd2g=
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://time.onrender.com
      - key: LOG_CHANNEL
        value: stderr
